### ISSUE TITLE
Order of operations when using MAP does not evaluate in an anticipatable way

### ISSUE THREAD

**Issue by RyanFleck** [Xalgorithms/lib-rules-int-scala#16]
When applying a MAP operation to a table, the USING statements are not applied in series. The following snippet should return `transaction:subtotal` multiplied by `EffectivePrice`, but does not:
```
MAP table:apply_vat
  USING EffectivePrice = add(1, multiply(divide(1, 100), @HST))
  USING Total = multiply(@EffectivePrice, transaction:subtotal);
```

Running this statement results in the following output:
```
HST: 13 | EffectivePrice: 1.13 | Total:  10.00
```

The correct output is:
```
HST: 13 | EffectivePrice: 1.13 | Total:  11.3000
```

The correct output can be produced by using separate MAP operations:
```
MAP table:apply_vat
  USING EffectivePrice = add(1, multiply(divide(1, 100), @HST));

MAP table:apply_vat
  USING Total = multiply(@EffectivePrice, transaction:subtotal);
```

The question here being, is this correct behaviour? I feel map operations should be applied in sequence, but I may be misunderstanding how to use the operation.

Rule used: [tax.zip](https://github.com/Xalgorithms/lib-rules-int-scala/files/2613606/tax.zip)

**Comment by karfai** [comment]
This is good stuff. Your assumption is correct. I'll put this in the 0.0.4 release series.

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.
